### ISSUE TITLE
Windows installer fails if chia or other chia forks are running

### ISSUE THREAD

**Issue by Bibosoft** [ball-network/seacoin-blockchain#1]
These processes has the same name on all forks. 

![image](https://github.com/ball-network/seacoin-blockchain/assets/139614350/47fbe80f-0f73-416e-9895-daaa75b961f7)

**Comment by palec2006** [comment]
зато быстро и одинаково

**Comment by ball-network** [comment]
This issue has been resolved and will be closed by [Release 2.0.0](https://github.com/<username>/<repository>/releases/tag/2.0.0).
